const buttonFilled: object = {
  white: {
    backgroud: "tw-bg-white",
    color: "tw-text-blue-gray-900",
    shadow: "tw-shadow-md tw-shadow-blue-gray-500/10",
    hover: "hover:tw-shadow-lg hover:tw-shadow-blue-gray-500/20",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  "blue-gray": {
    backgroud: "tw-bg-blue-gray-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-blue-gray-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-blue-gray-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  gray: {
    backgroud: "tw-bg-gray-900",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-gray-900/10",
    hover: "hover:tw-shadow-lg hover:tw-shadow-gray-900/20",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  brown: {
    backgroud: "tw-bg-brown-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-brown-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-brown-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  "deep-orange": {
    backgroud: "tw-bg-deep-orange-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-deep-orange-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-deep-orange-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  orange: {
    backgroud: "tw-bg-orange-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-orange-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-orange-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  amber: {
    backgroud: "tw-bg-amber-500",
    color: "tw-text-black",
    shadow: "tw-shadow-md tw-shadow-amber-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-amber-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  yellow: {
    backgroud: "tw-bg-yellow-500",
    color: "tw-text-black",
    shadow: "tw-shadow-md tw-shadow-yellow-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-yellow-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  lime: {
    backgroud: "tw-bg-lime-500",
    color: "tw-text-black",
    shadow: "tw-shadow-md tw-shadow-lime-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-lime-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  "light-green": {
    backgroud: "tw-bg-light-green-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-light-green-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-light-green-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  green: {
    backgroud: "tw-bg-green-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-green-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-green-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  teal: {
    backgroud: "tw-bg-teal-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-teal-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-teal-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  cyan: {
    backgroud: "tw-bg-cyan-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-cyan-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-cyan-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  "light-blue": {
    backgroud: "tw-bg-light-blue-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-light-blue-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-light-blue-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  blue: {
    backgroud: "tw-bg-blue-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-blue-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-blue-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  indigo: {
    backgroud: "tw-bg-indigo-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-indigo-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-indigo-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  "deep-purple": {
    backgroud: "tw-bg-deep-purple-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-deep-purple-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-deep-purple-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  purple: {
    backgroud: "tw-bg-purple-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-purple-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-purple-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  pink: {
    backgroud: "tw-bg-pink-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-pink-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-pink-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  red: {
    backgroud: "tw-bg-red-500",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-red-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-red-500/40",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
};

export default buttonFilled;
