const buttonOutlined: object = {
  white: {
    border: "tw-border tw-border-white",
    color: "tw-text-white",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-white/50",
    active: "active:tw-opacity-[0.85]",
  },
  "blue-gray": {
    border: "tw-border tw-border-blue-gray-500",
    color: "tw-text-blue-gray-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-blue-gray-200",
    active: "active:tw-opacity-[0.85]",
  },
  gray: {
    border: "tw-border tw-border-gray-900",
    color: "tw-text-gray-900",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-gray-300",
    active: "active:tw-opacity-[0.85]",
  },
  brown: {
    border: "tw-border tw-border-brown-500",
    color: "tw-text-brown-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-brown-200",
    active: "active:tw-opacity-[0.85]",
  },
  "deep-orange": {
    border: "tw-border tw-border-deep-orange-500",
    color: "tw-text-deep-orange-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-deep-orange-200",
    active: "active:tw-opacity-[0.85]",
  },
  orange: {
    border: "tw-border tw-border-orange-500",
    color: "tw-text-orange-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-orange-200",
    active: "active:tw-opacity-[0.85]",
  },
  amber: {
    border: "tw-border tw-border-amber-500",
    color: "tw-text-amber-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-amber-200",
    active: "active:tw-opacity-[0.85]",
  },
  yellow: {
    border: "tw-border tw-border-yellow-500",
    color: "tw-text-yellow-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-yellow-200",
    active: "active:tw-opacity-[0.85]",
  },
  lime: {
    border: "tw-border tw-border-lime-500",
    color: "tw-text-lime-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-lime-200",
    active: "active:tw-opacity-[0.85]",
  },
  "light-green": {
    border: "tw-border tw-border-light-green-500",
    color: "tw-text-light-green-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-light-green-200",
    active: "active:tw-opacity-[0.85]",
  },
  green: {
    border: "tw-border tw-border-green-500",
    color: "tw-text-green-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-green-200",
    active: "active:tw-opacity-[0.85]",
  },
  teal: {
    border: "tw-border tw-border-teal-500",
    color: "tw-text-teal-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-teal-200",
    active: "active:tw-opacity-[0.85]",
  },
  cyan: {
    border: "tw-border tw-border-cyan-500",
    color: "tw-text-cyan-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-cyan-200",
    active: "active:tw-opacity-[0.85]",
  },
  "light-blue": {
    border: "tw-border tw-border-light-blue-500",
    color: "tw-text-light-blue-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-light-blue-200",
    active: "active:tw-opacity-[0.85]",
  },
  blue: {
    border: "tw-border tw-border-blue-500",
    color: "tw-text-blue-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-blue-200",
    active: "active:tw-opacity-[0.85]",
  },
  indigo: {
    border: "tw-border tw-border-indigo-500",
    color: "tw-text-indigo-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-indigo-200",
    active: "active:tw-opacity-[0.85]",
  },
  "deep-purple": {
    border: "tw-border tw-border-deep-purple-500",
    color: "tw-text-deep-purple-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-deep-purple-200",
    active: "active:tw-opacity-[0.85]",
  },
  purple: {
    border: "tw-border tw-border-purple-500",
    color: "tw-text-purple-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-purple-200",
    active: "active:tw-opacity-[0.85]",
  },
  pink: {
    border: "tw-border tw-border-pink-500",
    color: "tw-text-pink-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-pink-200",
    active: "active:tw-opacity-[0.85]",
  },
  red: {
    border: "tw-border tw-border-red-500",
    color: "tw-text-red-500",
    hover: "hover:tw-opacity-75",
    focus: "focus:tw-ring focus:tw-ring-red-200",
    active: "active:tw-opacity-[0.85]",
  },
};

export default buttonOutlined;
