const buttonGradient: object = {
  white: {
    backgroud: "tw-bg-white",
    color: "tw-text-blue-gray-900",
    shadow: "tw-shadow-md tw-shadow-blue-gray-500/10",
    hover: "hover:tw-shadow-lg hover:tw-shadow-blue-gray-500/20",
    focus: "focus:tw-opacity-[0.85] focus:tw-shadow-none",
    active: "active:tw-opacity-[0.85] active:tw-shadow-none",
  },
  "blue-gray": {
    backgroud: "tw-bg-gradient-to-tr tw-from-blue-gray-600 tw-to-blue-gray-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-blue-gray-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-blue-gray-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  gray: {
    backgroud: "tw-bg-gradient-to-tr tw-from-gray-900 tw-to-gray-800",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-gray-900/10",
    hover: "hover:tw-shadow-lg hover:tw-shadow-gray-900/20",
    active: "active:tw-opacity-[0.85]",
  },
  brown: {
    backgroud: "tw-bg-gradient-to-tr tw-from-brown-600 tw-to-brown-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-brown-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-brown-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  "deep-orange": {
    backgroud:
      "tw-bg-gradient-to-tr tw-from-deep-orange-600 tw-to-deep-orange-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-deep-orange-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-deep-orange-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  orange: {
    backgroud: "tw-bg-gradient-to-tr tw-from-orange-600 tw-to-orange-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-orange-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-orange-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  amber: {
    backgroud: "tw-bg-gradient-to-tr tw-from-amber-600 tw-to-amber-400",
    color: "tw-text-black",
    shadow: "tw-shadow-md tw-shadow-amber-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-amber-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  yellow: {
    backgroud: "tw-bg-gradient-to-tr tw-from-yellow-600 tw-to-yellow-400",
    color: "tw-text-black",
    shadow: "tw-shadow-md tw-shadow-yellow-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-yellow-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  lime: {
    backgroud: "tw-bg-gradient-to-tr tw-from-lime-600 tw-to-lime-400",
    color: "tw-text-black",
    shadow: "tw-shadow-md tw-shadow-lime-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-lime-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  "light-green": {
    backgroud:
      "tw-bg-gradient-to-tr tw-from-light-green-600 tw-to-light-green-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-light-green-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-light-green-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  green: {
    backgroud: "tw-bg-gradient-to-tr tw-from-green-600 tw-to-green-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-green-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-green-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  teal: {
    backgroud: "tw-bg-gradient-to-tr tw-from-teal-600 tw-to-teal-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-teal-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-teal-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  cyan: {
    backgroud: "tw-bg-gradient-to-tr tw-from-cyan-600 tw-to-cyan-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-cyan-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-cyan-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  "light-blue": {
    backgroud:
      "tw-bg-gradient-to-tr tw-from-light-blue-600 tw-to-light-blue-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-light-blue-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-light-blue-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  blue: {
    backgroud: "tw-bg-gradient-to-tr tw-from-blue-600 tw-to-blue-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-blue-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-blue-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  indigo: {
    backgroud: "tw-bg-gradient-to-tr tw-from-indigo-600 tw-to-indigo-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-indigo-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-indigo-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  "deep-purple": {
    backgroud:
      "tw-bg-gradient-to-tr tw-from-deep-purple-600 tw-to-deep-purple-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-deep-purple-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-deep-purple-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  purple: {
    backgroud: "tw-bg-gradient-to-tr tw-from-purple-600 tw-to-purple-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-purple-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-purple-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  pink: {
    backgroud: "tw-bg-gradient-to-tr tw-from-pink-600 tw-to-pink-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-pink-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-pink-500/40",
    active: "active:tw-opacity-[0.85]",
  },
  red: {
    backgroud: "tw-bg-gradient-to-tr tw-from-red-600 tw-to-red-400",
    color: "tw-text-white",
    shadow: "tw-shadow-md tw-shadow-red-500/20",
    hover: "hover:tw-shadow-lg hover:tw-shadow-red-500/40",
    active: "active:tw-opacity-[0.85]",
  },
};

export default buttonGradient;
